CREATE TABLE IF NOT EXISTS TblOrganisor (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE,
	PhoneNumber VARCHAR(255) NOT NULL UNIQUE,
	Image VARCHAR(255) NOT NULL,
)
